# Generated by Django 3.2.6 on 2022-09-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_rename_roomname_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(default='University of Waterloo', max_length=30),
            preserve_default=False,
        ),
    ]
